### ISSUE TITLE
Where can I get this latest version with these new implementations to test ?

### ISSUE THREAD

**Issue by luapfr** [PasteBar/PasteBarApp#256]
Where can I get this latest version with these new implementations to test ?

**Comment by kurdin** [comment]
@luapfr I'll release it soon. What OS are you using ? I can create a beta build for you to test.

**Comment by luapfr** [comment]
> [@luapfr](https://github.com/luapfr) I'll release it soon. What OS are you using ? I can create a beta build for you to test.

Windows 11 64 bits

**Comment by kurdin** [comment]
@luapfr Thank you for testing. There is no user-defined limit for preview. Not sure why you should need it; this is just a preview. You can click +14 lines to see all or use a large view as you have it on the image.

**Comment by luapfr** [comment]
> [@luapfr](https://github.com/luapfr) Thank you for testing. There is no user-defined limit for preview. Not sure why you should need it; this is just a preview. You can click +14 lines to see all or use a large view as you have it on the image.

I actually want to reduce the size of the view to just 2 lines because I will always see the entire size on the side, but I know that other users will want it bigger, so it would be interesting to have a configuration so that the user can define how many lines to view.

**Comment by kurdin** [comment]
@luapfr  yeah, I understand, I see if I can make if as user preference.

**Comment by kurdin** [comment]
@luapfr I have implemented user settings for `History Item Preview Max Lines`. 
I'll create a test build for you tomorrow to test this out.

**Comment by luapfr** [comment]
> [@luapfr](https://github.com/luapfr) please try: https://github.com/PasteBar/Betas/releases/tag/v0.7.0-beta.2
> 
> this beta includes new options
> 

This new option is great and I'm already testing it.

Now I see this error where it simply stops scrolling items and I don't know why this happens.

https://github.com/user-attachments/assets/0f081e48-b973-4778-b8e0-f6092d829474

**Comment by kurdin** [comment]
@luapfr 
Please try this version. I fixed the issue and added support for Page Up / Page Down, Home, Del, Space (Select) keys in history items navigation. You can press Alt + Arrow Down to show context menu. 

https://github.com/PasteBar/Betas/releases/tag/v0.7.0-beta.3

**Comment by luapfr** [comment]
> [@luapfr](https://github.com/luapfr) Please try this version. I fixed the issue and added support for Page Up / Page Down, Home, Del, Space (Select) keys in history items navigation. You can press Alt + Arrow Down to show context menu.
> 
> https://github.com/PasteBar/Betas/releases/tag/v0.7.0-beta.3

I just installed it and it is still not possible to select an item with the mouse
For example, if I scroll the scroll bar and click on an item with the mouse, it does not receive Focus
See this attached video with a comparison with "CopyQ"


https://github.com/user-attachments/assets/d211783a-9db1-4a36-91e8-4ca34d8d27fa

**Comment by kurdin** [comment]
@luapfr 
https://github.com/PasteBar/Betas/releases/tag/v0.7.0-beta.5

Thank you for testing.

**Comment by kurdin** [comment]
@luapfr Thank you for testing, you don't have to press  "Shift + Ctrl" and click at all. It does not give you anything but keyboard focus, I am not sure why do you want to use mouse, click on the item and then use keyboard, what is your pattern ? Just use keyboard or mouse. Do what you want to do without pressing "Shift + Ctrl" + click. I don't want to change regular, single mouse click to select item for keyboard access, it does not needed and does not make any UX sense.

**Comment by luapfr** [comment]
> ![Image](https://github.com/user-attachments/assets/b8a2a0fc-63b5-47be-8315-ab9230381aa1) [@luapfr](https://github.com/luapfr) turn this option and try new beta please
> 
> https://github.com/PasteBar/Betas/releases/tag/v0.7.0-beta.6

Best

**Comment by luapfr** [comment]
> ![Image](https://github.com/user-attachments/assets/b8a2a0fc-63b5-47be-8315-ab9230381aa1) [@luapfr](https://github.com/luapfr) turn this option and try new beta please
> 
> https://github.com/PasteBar/Betas/releases/tag/v0.7.0-beta.6

It turned out great
